
export const QUERY_MAP = 'QUERY_MAP';
export const TABLE_VISIBLE_ROWS_CHANGE_MAP = 'TABLE_VISIBLE_ROWS_CHANGE_MAP';
export const CHANGE_BOUNDS_MAP = 'CHANGE_BOUNDS_MAP';
export const TABLE_HOVERED_ROWS_INDEX_CHANGE_MAP = 'TABLE_HOVERED_ROWS_INDEX_CHANGE_MAP';
export const MARKER_HOVER_INDEX_CHANGE_MAP = 'MARKER_HOVER_INDEX_CHANGE_MAP';
export const SHOW_BALLON_MAP = 'SHOW_BALLON_MAP';
